global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@lksnetwork.io'
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'
  - match:
      alertname: LKSNetworkDown
    receiver: 'emergency-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://lks-monitoring:8082/api/alerts/webhook'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'ops@lksnetwork.io'
    subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Severity: {{ .CommonLabels.severity }}
      
      {{ range .Alerts }}
      Instance: {{ .Labels.instance }}
      Description: {{ .Annotations.description }}
      {{ end }}
  slack_configs:
  - channel: '#lks-alerts'
    title: '🚨 Critical Alert'
    text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    send_resolved: true
  webhook_configs:
  - url: 'http://lks-monitoring:8082/api/alerts/critical'
    send_resolved: true

- name: 'warning-alerts'
  slack_configs:
  - channel: '#lks-monitoring'
    title: '⚠️ Warning Alert'
    text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    send_resolved: true
  webhook_configs:
  - url: 'http://lks-monitoring:8082/api/alerts/warning'
    send_resolved: true

- name: 'emergency-alerts'
  email_configs:
  - to: 'emergency@lksnetwork.io'
    subject: '🆘 EMERGENCY: LKS Network Down'
    body: |
      EMERGENCY: LKS Network is completely down!
      
      {{ range .Alerts }}
      Instance: {{ .Labels.instance }}
      Description: {{ .Annotations.description }}
      Time: {{ .StartsAt }}
      {{ end }}
      
      Immediate action required!
  slack_configs:
  - channel: '#emergency'
    title: '🆘 EMERGENCY: Network Down'
    text: 'LKS Network is down! Immediate attention required.'
    send_resolved: true
  webhook_configs:
  - url: 'http://lks-monitoring:8082/api/alerts/emergency'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
